-- 코드를 입력하세요
SELECT DISTINCT A.USER_ID
        , A.NICKNAME
        , A.ADRESS AS 전체주소
        , A.PHONE AS 전화번호
FROM(
SELECT UGU.USER_ID
            , UGU.NICKNAME
             , CITY||' '||STREET_ADDRESS1 ||' '|| STREET_ADDRESS2 AS ADRESS
             ,  SUBSTR(TLNO, 0,3)||'-'||SUBSTR(TLNO, 4,4)||'-'||SUBSTR(TLNO, 8,4) AS PHONE
            , COUNT(*) OVER (PARTITION BY USER_ID) AS CNT
FROM USED_GOODS_USER UGU
INNER JOIN USED_GOODS_BOARD UGB
ON UGB.WRITER_ID = UGU.USER_ID
    ) A
WHERE A.CNT > 2
ORDER BY A.USER_ID DESC