-- 코드를 입력하세요
SELECT CASE
       WHEN TO_CHAR(DATETIME,'HH24') LIKE '0%'THEN SUBSTR(TO_CHAR(DATETIME,'HH24'),2,2)
       ELSE TO_CHAR(DATETIME,'HH24')
       END AS HOUR
     , COUNT(DATETIME)
  FROM ANIMAL_OUTS
 GROUP BY TO_CHAR(DATETIME,'HH24')
 HAVING TO_CHAR(DATETIME,'HH24') BETWEEN '09' AND '19'
ORDER BY TO_CHAR(DATETIME,'HH24')