SELECT DISTINCT(a.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR a, CAR_RENTAL_COMPANY_RENTAL_HISTORY b
WHERE a.CAR_ID = b.CAR_ID
AND CAR_TYPE LIKE '세단'
AND DATE_FORMAT(START_DATE, '%m') = '10'
ORDER BY CAR_ID DESC;